name: 'Tests: SES'

on: [pull_request, push]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - '14'
          - '12'

    steps:
      - uses: actions/checkout@v2
      - uses: ljharb/actions/node/install@main
        name: 'nvm install ${{ matrix.node-version }} && npm install'
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run test:ses
      - uses: codecov/codecov-action@v2

  SES:
    permissions:
      contents: none
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
